CREATE TABLE USERS (
  ID integer PRIMARY KEY,
  HISTORY text,
  MESSAGES text,
  FIRST_NAME text,
  LAST_NAME text,
  USER_NAME text
);


CREATE TABLE CATEGORY_INCOME (
  ID integer PRIMARY KEY,
  USER_ID integer REFERENCES USERS(ID),
  NAME text
);

CREATE TABLE CATEGORY_OUTLAY (
  ID integer PRIMARY KEY,
  USER_ID integer REFERENCES USERS(ID),
  NAME text
);

CREATE TABLE OUTLAY (
  ID integer PRIMARY KEY,
  USER_ID integer REFERENCES USERS(ID),
  DATA_TIME date,
  SUM real,
  NAME_BANK text,
  RECIPIENT_FUNDS text,
  CATEGORY_OUT integer REFERENCES CATEGORY_OUTLAY(ID)
);

CREATE TABLE INCOME (
  ID integer PRIMARY KEY,
  USER_ID integer REFERENCES USERS(ID),
  DATE_TIME date,
  SUM real,
  NAME_BANK text,
  SENDER_FUNDS text,
  CATEGORY_IN integer REFERENCES CATEGORY_INCOME(ID)
);


CREATE TABLE GOAL (
  ID integer PRIMARY KEY,
  USER_ID integer REFERENCES USERS(ID),
  GOAL_NAME text,
  SUM_GOAL real,
  INCOME_USER real,
  INCOME_FREQUENCY integer,
  DURATION integer,
  REMINDER_DAYS text,
  REMINDER_TIME text,
  DATA_FINISH text,
  STATUS_GOAL text
);
